checkpoint_path: null

debug: false
model_name: &model_name unetpp
dataset_name: Vaihingen
max_epochs: 50
save_top_k: 1
batch_size: 32
grad_accumulation_batches: 32
lr: 1e-3
weight_decay: 1e-4
precision: bf16-mixed

in_channels: &in_channels 3
n_classes: &n_classes 6

###############################
# Modifiable Parameters:
###############################
patch_size: 256
overlap: 128

use_scheduler: true
scheduler_monitor: val_metrics/miou
lr_scheduler_kwargs: 
  mode: max
  factor: 0.5
  patience: 5
  threshold: 0.005
  threshold_mode: abs
  min_lr: 1e-6

loss_function: dice_loss ## cross_entropy, dice_loss, focal_loss, etc.
loss_kwargs:
  mode: multiclass
  classes: *n_classes
  from_logits: true
  smooth: 1e-8

model: *model_name
model_kwargs:
  encoder_name: efficientnet-b7
  encoder_depth: 5
  encoder_weights: imagenet
  in_channels: *in_channels
  classes: *n_classes