version: 1
project_name: deadtrees_segmentation
model_name: regular_unet
resume: False
fast_dev_run: False
overfit_batches: 0
seed: 42

data:
  train_image_glob: "DeadTrees/train/images/*.tif"
  train_mask_glob: "DeadTrees/train/masks/*.tif"
  val_image_glob: "DeadTrees/val/images/*.tif"
  val_mask_glob: "DeadTrees/val/masks/*.tif"
  dataset_cls: DeadTrees
  white_threshold: 0.1

model:
  encoder_name: resnet34
  encoder_weights: imagenet
  in_channels: 3
  classes: 2

augmentation:
  apply: False
  horizontal_flip_kwargs: 
    p: 0.5
  vertical_flip_kwargs:
    p: 0.5
  color_jitter_kwargs:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
    p: 0.8
    
  random_noise_kwargs:
    mean: 0.0
    std: 0.05
    p: 0.5

architecture:
  criterion: DiceLoss
  criterion_kwargs:
    mode: binary
  optimizer: AdamW
  optimizer_kwargs:
    lr: !!float 1e-3
    weight_decay: !!float 1e-5
  metrics: MeanIoU
  metrics_kwargs:
    num_classes: 2
    include_background: False
  add_channel_dim: True ## Necessary when using Dice Loss

trainer:
  n_tb_images: 4
  tb_size: [128, 128]
  accelerator: gpu
  devices: 1
  batch_size: 16
  pin_memory: True
  num_workers: 10
  num_epochs: 20
  accumulate_grad_batches: 4
  precision: 16-mixed
